homeassistant:
  name: My Smart Home
  country: UA
  currency: UAH
  language: en
  elevation: 179
  unit_system: metric
  time_zone: Europe/Kyiv
  customize: !include customize.yaml
  packages: !include_dir_merge_named includes/packages  

  # Loads default set of integrations. Do not remove.
default_config:

  # Load frontend themes from the themes folder
  frontend:
    themes: !include_dir_merge_named themes
    extra_module_url: /www/community/lovelace-card-mod/card-mod.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
influxdb: !include influxdb.yaml
recorder:
  purge_keep_days: 30
